'use strict';

/**
 * Builds the app configuration from an app-template 'app.config.json'.
 */

var fs = require('fs-extra');
var path = require('path');
var shell = require('shelljs');
var utils = require(path.resolve(__dirname, './utils'));

var APP_PATH = './app/';
var APP_CONFIG_PATH = './app-config/';

var getCommitHash = function() {
  //exec git command to get the hash of the current commit
  //git rev-parse HEAD
  var hash = shell.exec('git rev-parse HEAD', {
    silent: true
  }).output.trim().substr(0, 7);
  return hash;
};

var buildAppConfig = function(mode) {
  if (mode == 'dev') {
    console.log('***** In development mode. For release mode use `grunt prod` OR `npm run start:release` *****');
  }

  var pkg = utils.readJSON('./package.json');

  var appConfig = utils.readJSON(APP_CONFIG_PATH + 'app.config.json');
  appConfig.commitHash = getCommitHash();

  if (mode == 'dev') {
    appConfig.isDevelopmentMode = true;
  }

  console.log('v' + appConfig.version + ' #' + appConfig.commitHash + ' App:' + appConfig.name);

  var content = '';
  content += '\'use strict\';\n\n';
  content += '// Do not edit, this file is auto-generated by grunt.\n\n';
  content += 'angular.module(\'owsWalletApp\').constant(\'appConfig\', \n';
  content += utils.cleanJSONQuotesOnKeys(JSON.stringify(appConfig, null, 2));
  content += ');\n';

  fs.writeFileSync(APP_PATH + 'app.config.js', content);
	return appConfig;
};

module.exports = {
  build: buildAppConfig
};
